//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankEntities : DbContext
    {
        public bankEntities()
            : base("name=bankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bnkAccount> bnkAccounts { get; set; }
        public virtual DbSet<bnkBranch> bnkBranches { get; set; }
        public virtual DbSet<bnkCustomer> bnkCustomers { get; set; }
        public virtual DbSet<bnkEmployee> bnkEmployees { get; set; }
        public virtual DbSet<bnkServiceChargeManager> bnkServiceChargeManagers { get; set; }
        public virtual DbSet<bnkTransaction> bnkTransactions { get; set; }
        public virtual DbSet<bnkTransactionType> bnkTransactionTypes { get; set; }
    }
}
