//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkAccount
    {
        public int AccountID { get; set; }
        public System.Guid AccountTicket { get; set; }
        public int CustomerID { get; set; }
        public string AccountStatus { get; set; }
        public double BalanceAvailable { get; set; }
        public double BalancePending { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public int BranchID { get; set; }
        public int EmployeeID { get; set; }
    }
}
