//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkEmployee
    {
        public int EmployeeID { get; set; }
        public System.Guid EmployeeTicket { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public string Title { get; set; }
        public string TIN { get; set; }
    }
}
