//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkServiceChargeManager
    {
        public int ServiceChargeManagerID { get; set; }
        public System.Guid ServiceChargeManagerTicket { get; set; }
        public int AccountID { get; set; }
        public string ServiceChargeExpression { get; set; }
    }
}
