//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkTransactionType
    {
        public int TransactionTypeID { get; set; }
        public System.Guid TransactionTypeTicket { get; set; }
        public int TransactionTypeEnum { get; set; }
        public int TransactionTypeSortIndex { get; set; }
        public string TransactionTypeName { get; set; }
        public string TransactionTypeDescription { get; set; }
    }
}
