//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bnkTransaction
    {
        public int TransactionID { get; set; }
        public System.Guid TransactionTicket { get; set; }
        public int AccountID { get; set; }
        public int TransactionTypeEnum { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<System.DateTime> DateFundsAvailable { get; set; }
        public string RemoteInstitution { get; set; }
        public string RemoteAccount { get; set; }
    }
}
